services:
  - type: web
    name: projectgoat
    env: python
    region: oregon
    plan: free
    buildCommand: 'pip install -r requirements-postgres.txt && npm install && npm run build'
    startCommand: 'python run.py'
    envVars:
      - key: PYTHON_VERSION
        value: '3.11.9'
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: '0.0.0.0'
      - key: DATABASE_URL
        fromDatabase:
          name: projectgoat-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PRODUCTION_ORIGIN
        sync: false

databases:
  - name: projectgoat-db
    databaseName: projectgoat
    plan: free
